spring:
  application:
    name: School Information System
  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username: abdul-razak
    password: 206207
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #          ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
